### ISSUE TITLE
Find command to see dependency graph in gradle

### ISSUE THREAD

**Issue by moglideveloper** [nehagandhi20/LearnGuava#10]
Find command to see dependency graph in gradle

**Comment by moglideveloper** [comment]
Solution :

gradle dependencies

or for specific configuration, you can use :-

gradle dependencies --configuration testCompile

**Comment by nehagandhi20** [comment]
moving to new repo

**Comment by nehagandhi20** [comment]
This issue was moved to moglideveloper/CollegeStyleStudy#12
