### ISSUE TITLE
Add slf4j logging support to gradle project

### ISSUE THREAD

**Issue by moglideveloper** [nehagandhi20/LearnGuava#12]
Add slf4j logging support to gradle project.
After completing this task, never use sysout in your logic.

**Comment by moglideveloper** [comment]
Basic program added to src/main/java

**Comment by nehagandhi20** [comment]
trying to move issue to new repo

**Comment by nehagandhi20** [comment]
This issue was moved to moglideveloper/CollegeStyleStudy#11
