### ISSUE TITLE
check java7 Objects class utility methods

### ISSUE THREAD

**Issue by moglideveloper** [nehagandhi20/LearnGuava#13]
For reference :-
http://baptiste-wicht.com/posts/2010/04/java-7-the-new-java-util-objects-class.html

Objects.equals methods looks very promising to me for writing clean code.

Also, check which is better feature wise (Guava Objects class or java7 Objects class).

I think, its better to use classes provided by java team.
Looking forward for your opinion on this ;).

**Comment by nehagandhi20** [comment]
Yes its better to use java 7 Objects class static methods rather than remembering library methods.

**Comment by nehagandhi20** [comment]
Do we need to add test cases for java 7 Objects class ?
If yes then in LearnGuava project or later on in Multithreading package ?

**Comment by moglideveloper** [comment]
Yes, for every new thing, that we plan to learn, we will write test cases.
No more demos :).
I think, for the time being we can keep misc. tests in "other.x" package in "LearnGuava" project and when the size of this "other" package will increased to significant bytes, then we can re-factor out this other package to meaningful project. I already created a task for this https://github.com/nehagandhi20/LearnGuava/issues/9.

Thanks.

**Comment by moglideveloper** [comment]
I am assigning this task to myself, as i had studied some methods. (just to avoid spending double efforts)
Test cases are in progress...

**Comment by nehagandhi20** [comment]
This issue was moved to moglideveloper/CollegeStyleStudy#4
