### ISSUE TITLE
write utility method for below functionality

### ISSUE THREAD

**Issue by moglideveloper** [nehagandhi20/LearnGuava#15]
@Override
	public boolean equals(Object obj) {
		Optional<Object> optional = Optional.fromNullable(obj);
		
		
		if(optional.isPresent() && optional.get().getClass().isAssignableFrom(this.getClass())){
			//here is business logic
		}else{
			return false ;
		}
		
	}

**Comment by nehagandhi20** [comment]
This issue was moved to moglideveloper/CollegeStyleStudy#2
