### ISSUE TITLE
Git tasks not synced

### ISSUE THREAD

**Issue by moglideveloper** [nehagandhi20/LearnGuava#3]
Git tasks not synced

**Comment by nehagandhi20** [comment]
Hi,

Now we can see all issues on Mylyn task list. Follow the below steps and
enjoy :)

1. We have to firstly make a query for the particular task repository by
right clicking on the repository.
2. Enter all required fields in the query and select the label i.e.
enhancement or help wanted etc.
3. Open task list and here you go...

Thanks,
Neha Gandhi

**Comment by moglideveloper** [comment]
It's now working on my machine. 
Thanks Neha :)

**Comment by moglideveloper** [comment]
Mapping assignee to neha, as she worked on this task.

**Comment by nehagandhi20** [comment]
moving to new repo

**Comment by nehagandhi20** [comment]
This issue was moved to moglideveloper/CollegeStyleStudy#14
