### ISSUE TITLE
Many PreCondition methods are not covered yet

### ISSUE THREAD

**Issue by moglideveloper** [nehagandhi20/LearnGuava#8]
Request you to cover example of PreCondition API methods , that you think can be useful for us for writing quality code :).

**Comment by nehagandhi20** [comment]
checkPositionIndex() and checkState() methods are left. I will cover these asap.
Other Preconditions API methods were already covered in PreconditionsDemo.java (which was deleted :)...) but somehow not covered in test case.

**Comment by moglideveloper** [comment]
I think, its a good idea to include them in test cases :)

**Comment by nehagandhi20** [comment]
This issue was moved to moglideveloper/CollegeStyleStudy#6
